In [1]:
# Imporing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [127]:
# Loading dataset in 'df'

df=pd.read_csv('magic_bricks_cleandata.csv')

In [128]:
df

,Unnamed: 0,Area,BHK,Bathroom,Furnishing,Location,District,Locality,Parking,Status,Transaction,Type,Per_Sqft,Price
0,0,950.0,2,2.0,Furnished,Karol Bagh,Central Delhi,"DDA MIG Flats Prasad Nagar Phase 2, Prasad Nag...",1.0,Ready_to_move,Resale,Apartment,8761.0,12500000
1,1,535.0,2,1.0,Furnished,Karol Bagh,Central Delhi,"Dev Nagar, Karol Bagh",1.0,Ready_to_move,New_Property,Apartment,7290.0,3900000
2,2,1280.0,3,3.0,Furnished,Karol Bagh,Central Delhi,Karol Bagh,2.0,Ready_to_move,Resale,Builder_Floor,14092.0,15000000
3,3,1135.0,3,3.0,Furnished,Karol Bagh,Central Delhi,"The Amaryllis, Karol Bagh",2.0,Almost_ready,Resale,Apartment,22222.0,25000000
4,4,1135.0,3,3.0,Furnished,Karol Bagh,Central Delhi,"The Amaryllis, Karol Bagh",2.0,Almost_ready,Resale,Apartment,22222.0,25000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,1209,4688.0,5,4.0,Unfurnished,Patel Nagar,West Delhi,"The Leela Sky Villas, Patel Nagar",1.0,Almost_ready,New_Property,Apartment,28797.0,135000000
1210,1210,3901.0,4,4.0,Unfurnished,Patel Nagar,West Delhi,"The Leela Sky Villas, Patel Nagar",1.0,Almost_ready,New_Property,Apartment,23840.0,93000000
1211,1211,2306.0,3,3.0,Unfurnished,Patel Nagar,West Delhi,"The Leela Sky Villas, Patel Nagar",1.0,Almost_ready,New_Property,Apartment,24718.0,57000000
1212,1212,675.0,2,1.0,Unfurnished,Uttam Nagar,West Delhi,Uttam Nagar,1.0,Ready_to_move,Resale,Builder_Floor,5794.0,2900000
1213,1213,585.0,2,2.0,Unfurnished,Uttam Nagar,West Delhi,Uttam Nagar,1.0,Ready_to_move,Resale,Builder_Floor,5794.0,3200000

In [129]:
# using ordinal encoder

from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df[['Furnishing','District','Status','Transaction','Location','Type']]=oe.fit_transform(df[['Furnishing','District','Status','Transaction','Location','Type']])

In [130]:
df

,Unnamed: 0,Area,BHK,Bathroom,Furnishing,Location,District,Locality,Parking,Status,Transaction,Type,Per_Sqft,Price
0,0,950.0,2,2.0,0.0,12.0,0.0,"DDA MIG Flats Prasad Nagar Phase 2, Prasad Nag...",1.0,1.0,1.0,0.0,8761.0,12500000
1,1,535.0,2,1.0,0.0,12.0,0.0,"Dev Nagar, Karol Bagh",1.0,1.0,0.0,0.0,7290.0,3900000
2,2,1280.0,3,3.0,0.0,12.0,0.0,Karol Bagh,2.0,1.0,1.0,1.0,14092.0,15000000
3,3,1135.0,3,3.0,0.0,12.0,0.0,"The Amaryllis, Karol Bagh",2.0,0.0,1.0,0.0,22222.0,25000000
4,4,1135.0,3,3.0,0.0,12.0,0.0,"The Amaryllis, Karol Bagh",2.0,0.0,1.0,0.0,22222.0,25000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1209,1209,4688.0,5,4.0,2.0,23.0,8.0,"The Leela Sky Villas, Patel Nagar",1.0,0.0,0.0,0.0,28797.0,135000000
1210,1210,3901.0,4,4.0,2.0,23.0,8.0,"The Leela Sky Villas, Patel Nagar",1.0,0.0,0.0,0.0,23840.0,93000000
1211,1211,2306.0,3,3.0,2.0,23.0,8.0,"The Leela Sky Villas, Patel Nagar",1.0,0.0,0.0,0.0,24718.0,57000000
1212,1212,675.0,2,1.0,2.0,32.0,8.0,Uttam Nagar,1.0,1.0,1.0,1.0,5794.0,2900000
1213,1213,585.0,2,2.0,2.0,32.0,8.0,Uttam Nagar,1.0,1.0,1.0,1.0,5794.0,3200000

In [131]:
# making independent and dependent variables

x=df.drop(['Price','Locality','Unnamed: 0'],axis=1)
y=df.Price

In [132]:
# importing train_test_split from model selection
from sklearn.model_selection import train_test_split

In [133]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)

In [134]:
# Importing decision tree regressor

from sklearn.tree import DecisionTreeRegressor

In [135]:
# putting the algorithm in variable 'dtr'

dtr=DecisionTreeRegressor()

In [136]:
# fitting training data

dtr.fit(x_train,y_train)

DecisionTreeRegressor()

In [137]:
# predicting

y_pred=dtr.predict(x_test)

In [138]:
# checking accuracy

from sklearn.metrics import r2_score

In [139]:
r2_score(y_test,y_pred).round(2)

0.85